### ISSUE TITLE
Memory leak in calico-kube-controllers

### ISSUE THREAD

**Issue by hangzhouwanjun** [projectcalico/kube-controllers#634]
When use calico-kube-controllers（v1.15.1）, it has memory leak
## Expected Behavior

It has no memory leak
## Current Behavior

Memory usage such as:
```
(1) kubernetes top show
calico-kube-controllers-6f59b8cdd8-8gw8x   5m           **81743Mi**

```

```
(2) docker stats show
629e870475dd        k8s_calico-kube-controllers_calico-kube-controllers-6f59b8cdd8-8gw8x_kube-system_d60788b6-66b2-4fcd-a9b6-38f117e5df73_0                                   0.40%               **79.83GiB / 251.3GiB**   31.76%              0B / 0B             214MB / 0B          88
```

## Possible Solution

There has some go stack log：

```
runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x164c720), concrete:(*runtime._type)(0x16f4600), asserted:(*runtime._type)(0x185eb00), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)
goroutine 258 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1692b80, 0xc0016a2ab0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1692b80, 0xc0016a2ab0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/projectcalico/kube-controllers/pkg/controllers/pod.NewPodController.func4(0x16f4600, 0xc0014d38a0)
        /go/src/github.com/projectcalico/kube-controllers/pkg/controllers/pod/pod_controller.go:171 +0x566
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
        /go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:212
k8s.io/client-go/tools/cache.newInformer.func1(0x169e500, 0xc000f76720, 0x1, 0xc000f76720)
        /go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:376 +0x37f
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0006448f0, 0xc00063e750, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/delta_fifo.go:422 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000646180)
        /go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:153 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a6bfb0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000af3fb0, 0x3b9aca00, 0x0, 0xc0004a2401, 0xc000042300)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc000646180, 0xc000042300)
        /go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:125 +0x2fd
created by github.com/projectcalico/kube-controllers/pkg/controllers/pod.(*podController).Run
        /go/src/github.com/projectcalico/kube-controllers/pkg/controllers/pod/pod_controller.go:215 +0x27b
{"level":"warn","ts":"2021-01-21T03:22:54.089Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-40d95dc6-7a8a-4816-9908-264a0e445ba5/10.114.141.101:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

node will run out of memory

## Your Environment

* Kubernetes version (`kubectl version`): v1.15.12
* Manifest file used to deploy k8s policy:
* Operating System and version:centos 7.6
* Link to your project (optional):
calico-kube-controllers version：v1.15.1

**Comment by caseydavenport** [comment]
I recently merged this PR to fix a memory leak in kube-controllers: https://github.com/projectcalico/kube-controllers/pull/641

Not sure if it is the same one that you are hitting here. For what it is worth, it should be OK to set a memory limit on kube-controllers so that it reboots in the case of a leak. 

> runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x164c720), concrete:(*runtime._type)(0x16f4600), asserted:(*runtime._type)(0x185eb00), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Pod)

I am not sure if this is the same thing / related to the memory leak or not. It seems to be a bad type assertion here: https://github.com/projectcalico/kube-controllers/pull/641/files#diff-42241a9fa5875508aaacc5c82005e841d985d81bcec50553aba3afdc56ddc6acL171
